default: styles/Homestuck.scss
OriginalTrollian: styles/OriginalTrollian.scss
Trollian: styles/Trollian.scss
Pesterchum: styles/Pesterchum.scss
NewAlternian: styles/NewAlternian.scss
OldAlternian: styles/OldAlternian.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
Test: styles/Test.scss
